version: "3.7"

volumes:
  postgres:
  server_node_modules:

services:

  postgres:
    image: postgres:9.6.17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgres
    ports:
      - 5432

  # This container builds the server.
  server-builder:
    build:
      context: .
      target: base
    command: yarn build:development
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: server_node_modules
        target: /workspace/node_modules

  # This container runs the server.
  server:
    depends_on:
      - server-builder
      - postgres
    build:
      context: .
      target: base
    command: yarn start:development
    environment:
      NODE_ENV: development
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: server_node_modules
        target: /workspace/node_modules
    ports:
      - "8000:80"
